export const GET_ALL_CONTACTS_START = 'GET_ALL_CONTACTS_START';
export const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS';
export const GET_ALL_CONTACTS_FAIL = 'GET_ALL_CONTACTS_FAIL';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';